// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var IbPacket = IbPacket || {};

/**
 * @enum
 */
IbPacket.TickType = {
  BID_SIZE: 0,
  BID: 1,
  ASK: 2,
  ASK_SIZE: 3,
  LAST: 4,
  LAST_SIZE: 5,
  HIGH: 6,
  LOW: 7,
  VOLUME: 8,
  CLOSE: 9,
  BID_OPTION_COMPUTATION: 10,
  ASK_OPTION_COMPUTATION: 11,
  LAST_OPTION_COMPUTATION: 12,
  MODEL_OPTION: 13,
  OPEN: 14,
  LOW_13_WEEK: 15,
  HIGH_13_WEEK: 16,
  LOW_26_WEEK: 17,
  HIGH_26_WEEK: 18,
  LOW_52_WEEK: 19,
  HIGH_52_WEEK: 20,
  AVG_VOLUME: 21,
  OPEN_INTEREST: 22,
  OPTION_HISTORICAL_VOL: 23,
  OPTION_IMPLIED_VOL: 24,
  OPTION_BID_EXCH: 25,
  OPTION_ASK_EXCH: 26,
  OPTION_CALL_OPEN_INTEREST: 27,
  OPTION_PUT_OPEN_INTEREST: 28,
  OPTION_CALL_VOLUME: 29,
  OPTION_PUT_VOLUME: 30,
  INDEX_FUTURE_PREMIUM: 31,
  BID_EXCH: 32,
  ASK_EXCH: 33,
  AUCTION_VOLUME: 34,
  AUCTION_PRICE: 35,
  AUCTION_IMBALANCE: 36,
  MARK_PRICE: 37,
  BID_EFP_COMPUTATION: 38,
  ASK_EFP_COMPUTATION: 39,
  LAST_EFP_COMPUTATION: 40,
  OPEN_EFP_COMPUTATION: 41,
  HIGH_EFP_COMPUTATION: 42,
  LOW_EFP_COMPUTATION: 43,
  CLOSE_EFP_COMPUTATION: 44,
  LAST_TIMESTAMP: 45,
  SHORTABLE: 46,
  FUNDAMENTAL_RATIOS: 47,
  RT_VOLUME: 48,
  HALTED: 49,
  BID_YIELD: 50,
  ASK_YIELD: 51,
  LAST_YIELD: 52,
  CUST_OPTION_COMPUTATION: 53,
  TRADE_COUNT: 54,
  TRADE_RATE: 55,
  VOLUME_RATE: 56,
  LAST_RTH_TRADE: 57,
  RT_HISTORICAL_VOL: 58,
  IB_DIVIDENDS: 59,
  BOND_FACTOR_MULTIPLIER: 60,
  REGULATORY_IMBALANCE: 61,
  NEWS_TICK: 62,
  SHORT_TERM_VOLUME_3_MIN: 63,
  SHORT_TERM_VOLUME_5_MIN: 64,
  SHORT_TERM_VOLUME_10_MIN: 65,
  DELAYED_BID: 66,
  DELAYED_ASK: 67,
  DELAYED_LAST: 68,
  DELAYED_BID_SIZE: 69,
  DELAYED_ASK_SIZE: 70,
  DELAYED_LAST_SIZE: 71,
  DELAYED_HIGH: 72,
  DELAYED_LOW: 73,
  DELAYED_VOLUME: 74,
  DELAYED_CLOSE: 75,
  DELAYED_OPEN: 76,
  RT_TRD_VOLUME: 77,
  CREDITMAN_MARK_PRICE: 78,
  CREDITMAN_SLOW_MARK_PRICE: 79,
  NOT_SET: 80
};

/**
 * @enum
 */
IbPacket.Data = {
  NONE: 0,
  Info: 1,
  Scan: 2,
  MktTickSz: 3,
  MktTickPrc: 4,
  MktTickStr: 5,
  Tick: 6
};

/**
 * @enum
 */
IbPacket.Type = {
  Info: 0,
  Scan: 1,
  MktTickSz: 2,
  MktTickPrc: 3,
  MktTickStr: 4,
  Tick: 5
};

/**
 * @constructor
 */
IbPacket.Packet = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {IbPacket.Packet}
 */
IbPacket.Packet.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {IbPacket.Packet=} obj
 * @returns {IbPacket.Packet}
 */
IbPacket.Packet.getRootAsPacket = function(bb, obj) {
  return (obj || new IbPacket.Packet).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {IbPacket.Type}
 */
IbPacket.Packet.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {IbPacket.Type} */ (this.bb.readInt8(this.bb_pos + offset)) : IbPacket.Type.Info;
};

/**
 * @returns {flatbuffers.Long}
 */
IbPacket.Packet.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {IbPacket.Data}
 */
IbPacket.Packet.prototype.payloadType = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {IbPacket.Data} */ (this.bb.readUint8(this.bb_pos + offset)) : IbPacket.Data.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
IbPacket.Packet.prototype.payload = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
IbPacket.Packet.startPacket = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {IbPacket.Type} type
 */
IbPacket.Packet.addType = function(builder, type) {
  builder.addFieldInt8(0, type, IbPacket.Type.Info);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} time
 */
IbPacket.Packet.addTime = function(builder, time) {
  builder.addFieldInt64(1, time, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {IbPacket.Data} payloadType
 */
IbPacket.Packet.addPayloadType = function(builder, payloadType) {
  builder.addFieldInt8(2, payloadType, IbPacket.Data.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} payloadOffset
 */
IbPacket.Packet.addPayload = function(builder, payloadOffset) {
  builder.addFieldOffset(3, payloadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
IbPacket.Packet.endPacket = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
IbPacket.Packet.finishPacketBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @constructor
 */
IbPacket.Info = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {IbPacket.Info}
 */
IbPacket.Info.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {IbPacket.Info=} obj
 * @returns {IbPacket.Info}
 */
IbPacket.Info.getRootAsInfo = function(bb, obj) {
  return (obj || new IbPacket.Info).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
IbPacket.Info.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
IbPacket.Info.startInfo = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
IbPacket.Info.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
IbPacket.Info.endInfo = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
IbPacket.ActiveScan = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {IbPacket.ActiveScan}
 */
IbPacket.ActiveScan.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {IbPacket.ActiveScan=} obj
 * @returns {IbPacket.ActiveScan}
 */
IbPacket.ActiveScan.getRootAsActiveScan = function(bb, obj) {
  return (obj || new IbPacket.ActiveScan).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {IbPacket.Scan=} obj
 * @returns {IbPacket.Scan}
 */
IbPacket.ActiveScan.prototype.scans = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new IbPacket.Scan).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
IbPacket.ActiveScan.prototype.scansLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
IbPacket.ActiveScan.startActiveScan = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} scansOffset
 */
IbPacket.ActiveScan.addScans = function(builder, scansOffset) {
  builder.addFieldOffset(0, scansOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
IbPacket.ActiveScan.createScansVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
IbPacket.ActiveScan.startScansVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
IbPacket.ActiveScan.endActiveScan = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
IbPacket.Scan = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {IbPacket.Scan}
 */
IbPacket.Scan.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {IbPacket.Scan=} obj
 * @returns {IbPacket.Scan}
 */
IbPacket.Scan.getRootAsScan = function(bb, obj) {
  return (obj || new IbPacket.Scan).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
IbPacket.Scan.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
IbPacket.Scan.prototype.utime = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
IbPacket.Scan.prototype.symb = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
IbPacket.Scan.prototype.symbLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
IbPacket.Scan.startScan = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
IbPacket.Scan.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} utime
 */
IbPacket.Scan.addUtime = function(builder, utime) {
  builder.addFieldInt64(1, utime, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} symbOffset
 */
IbPacket.Scan.addSymb = function(builder, symbOffset) {
  builder.addFieldOffset(2, symbOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
IbPacket.Scan.createSymbVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
IbPacket.Scan.startSymbVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
IbPacket.Scan.endScan = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
IbPacket.MktTickSz = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {IbPacket.MktTickSz}
 */
IbPacket.MktTickSz.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {IbPacket.MktTickSz=} obj
 * @returns {IbPacket.MktTickSz}
 */
IbPacket.MktTickSz.getRootAsMktTickSz = function(bb, obj) {
  return (obj || new IbPacket.MktTickSz).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {IbPacket.TickType}
 */
IbPacket.MktTickSz.prototype.field = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {IbPacket.TickType} */ (this.bb.readInt8(this.bb_pos + offset)) : IbPacket.TickType.BID_SIZE;
};

/**
 * @returns {number}
 */
IbPacket.MktTickSz.prototype.size = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
IbPacket.MktTickSz.prototype.symbol = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
IbPacket.MktTickSz.prototype.utime = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
IbPacket.MktTickSz.startMktTickSz = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {IbPacket.TickType} field
 */
IbPacket.MktTickSz.addField = function(builder, field) {
  builder.addFieldInt8(0, field, IbPacket.TickType.BID_SIZE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} size
 */
IbPacket.MktTickSz.addSize = function(builder, size) {
  builder.addFieldInt32(1, size, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} symbolOffset
 */
IbPacket.MktTickSz.addSymbol = function(builder, symbolOffset) {
  builder.addFieldOffset(2, symbolOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} utime
 */
IbPacket.MktTickSz.addUtime = function(builder, utime) {
  builder.addFieldInt64(3, utime, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
IbPacket.MktTickSz.endMktTickSz = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
IbPacket.MktTickPrc = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {IbPacket.MktTickPrc}
 */
IbPacket.MktTickPrc.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {IbPacket.MktTickPrc=} obj
 * @returns {IbPacket.MktTickPrc}
 */
IbPacket.MktTickPrc.getRootAsMktTickPrc = function(bb, obj) {
  return (obj || new IbPacket.MktTickPrc).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {IbPacket.TickType}
 */
IbPacket.MktTickPrc.prototype.field = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {IbPacket.TickType} */ (this.bb.readInt8(this.bb_pos + offset)) : IbPacket.TickType.BID_SIZE;
};

/**
 * @returns {number}
 */
IbPacket.MktTickPrc.prototype.price = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {boolean}
 */
IbPacket.MktTickPrc.prototype.canAutoExecute = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
IbPacket.MktTickPrc.prototype.symbol = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
IbPacket.MktTickPrc.prototype.utime = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
IbPacket.MktTickPrc.startMktTickPrc = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {IbPacket.TickType} field
 */
IbPacket.MktTickPrc.addField = function(builder, field) {
  builder.addFieldInt8(0, field, IbPacket.TickType.BID_SIZE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} price
 */
IbPacket.MktTickPrc.addPrice = function(builder, price) {
  builder.addFieldFloat64(1, price, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} canAutoExecute
 */
IbPacket.MktTickPrc.addCanAutoExecute = function(builder, canAutoExecute) {
  builder.addFieldInt8(2, +canAutoExecute, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} symbolOffset
 */
IbPacket.MktTickPrc.addSymbol = function(builder, symbolOffset) {
  builder.addFieldOffset(3, symbolOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} utime
 */
IbPacket.MktTickPrc.addUtime = function(builder, utime) {
  builder.addFieldInt64(4, utime, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
IbPacket.MktTickPrc.endMktTickPrc = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
IbPacket.MktTickStr = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {IbPacket.MktTickStr}
 */
IbPacket.MktTickStr.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {IbPacket.MktTickStr=} obj
 * @returns {IbPacket.MktTickStr}
 */
IbPacket.MktTickStr.getRootAsMktTickStr = function(bb, obj) {
  return (obj || new IbPacket.MktTickStr).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {IbPacket.TickType}
 */
IbPacket.MktTickStr.prototype.field = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {IbPacket.TickType} */ (this.bb.readInt8(this.bb_pos + offset)) : IbPacket.TickType.BID_SIZE;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
IbPacket.MktTickStr.prototype.value = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
IbPacket.MktTickStr.prototype.symbol = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
IbPacket.MktTickStr.prototype.utime = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
IbPacket.MktTickStr.startMktTickStr = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {IbPacket.TickType} field
 */
IbPacket.MktTickStr.addField = function(builder, field) {
  builder.addFieldInt8(0, field, IbPacket.TickType.BID_SIZE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
IbPacket.MktTickStr.addValue = function(builder, valueOffset) {
  builder.addFieldOffset(1, valueOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} symbolOffset
 */
IbPacket.MktTickStr.addSymbol = function(builder, symbolOffset) {
  builder.addFieldOffset(2, symbolOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} utime
 */
IbPacket.MktTickStr.addUtime = function(builder, utime) {
  builder.addFieldInt64(3, utime, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
IbPacket.MktTickStr.endMktTickStr = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
IbPacket.Tick = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {IbPacket.Tick}
 */
IbPacket.Tick.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {IbPacket.Tick=} obj
 * @returns {IbPacket.Tick}
 */
IbPacket.Tick.getRootAsTick = function(bb, obj) {
  return (obj || new IbPacket.Tick).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
IbPacket.Tick.prototype.symb = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
IbPacket.Tick.prototype.datetime = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
IbPacket.Tick.prototype.open = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
IbPacket.Tick.prototype.high = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
IbPacket.Tick.prototype.low = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
IbPacket.Tick.prototype.close = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {flatbuffers.Long}
 */
IbPacket.Tick.prototype.volume = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
IbPacket.Tick.prototype.wap = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
IbPacket.Tick.prototype.count = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
IbPacket.Tick.startTick = function(builder) {
  builder.startObject(9);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} symbOffset
 */
IbPacket.Tick.addSymb = function(builder, symbOffset) {
  builder.addFieldOffset(0, symbOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} datetimeOffset
 */
IbPacket.Tick.addDatetime = function(builder, datetimeOffset) {
  builder.addFieldOffset(1, datetimeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} open
 */
IbPacket.Tick.addOpen = function(builder, open) {
  builder.addFieldFloat64(2, open, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} high
 */
IbPacket.Tick.addHigh = function(builder, high) {
  builder.addFieldFloat64(3, high, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} low
 */
IbPacket.Tick.addLow = function(builder, low) {
  builder.addFieldFloat64(4, low, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} close
 */
IbPacket.Tick.addClose = function(builder, close) {
  builder.addFieldFloat64(5, close, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} volume
 */
IbPacket.Tick.addVolume = function(builder, volume) {
  builder.addFieldInt64(6, volume, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} wap
 */
IbPacket.Tick.addWap = function(builder, wap) {
  builder.addFieldFloat64(7, wap, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} count
 */
IbPacket.Tick.addCount = function(builder, count) {
  builder.addFieldInt32(8, count, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
IbPacket.Tick.endTick = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.IbPacket = IbPacket;
